version: "3.8"

services:
  db:
    image: mariadb:jammy
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app/
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000


volumes:
  db_data:
    
